### ISSUE TITLE
LNK2019:unresolved external symbol "void_cdcl cv:...." in run the ch2 Hello_Qt_OpenCV

### ISSUE THREAD

**Issue by jingweimo** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#1]
I am running the example project `Hello_Qt_OpenCV `in ch02 in QtCreater4.5 with opencv3.2. The only change I made to the original `Hello_Qt_OpenCV .pro` file is the link to my opencv library. The configuration of opencv in Qt works fine with other qt projects. 

 Three issues are shown in building the project: 
`File not found: mainwindow.obj: LNK2019: unresolved external symbol "void __cdecl cv::medianBlur(class cv::_InputArray const &,class cv::_OutputArray const &,int)" (?medianBlur@cv@@YAXAEBV_InputArray@1@AEBV_OutputArray@1@H@Z) referenced in function "private: void __cdecl MainWindow::on_outputPushButton_pressed(void)" (?on_outputPushButton_pressed@MainWindow@@AEAAXXZ)`

`File not found: mainwindow.obj: LNK2019: unresolved external symbol "void __cdecl cv::GaussianBlur(class cv::_InputArray const &,class cv::_OutputArray const &,class cv::Size_<int>,double,double,int)" (?GaussianBlur@cv@@YAXAEBV_InputArray@1@AEBV_OutputArray@1@V?$Size_@H@1@NNH@Z) referenced in function "private: void __cdecl MainWindow::on_outputPushButton_pressed(void)" (?on_outputPushButton_pressed@MainWindow@@AEAAXXZ)`

`LNK1120: 2 unresolved externals  release\Hello_Qt_OpenCV.exe:-1: error`

I tried `clean`, `run qmake `and `build ` as suggested here: https://stackoverflow.com/questions/15864177/file-not-found-mainwindow-obj, but still cannot solve these issues.

**Comment by karlphillip** [comment]
Please share the contents of your .pro file here.

**Comment by jingweimo** [comment]
You are right!! I omitted the `imgproc320` library in my `.pri `file! By the way, your book is greatly helpful!!

**Comment by karlphillip** [comment]
Great! 

I just helped a little bit during the technical review process of the book but I am sure the author is super glad to hear that! 

Let us know when you have problems in the future.
See you around!

**Comment by amahta** [comment]
Thanks @karlphillip ,
@jingweimo I'll close this issue then!
