### ISSUE TITLE
Chapter 5: byteCount is deprecated

### ISSUE THREAD

**Issue by tomihasa** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#11]
In file qcustomgraphicseffect.cpp byteCount is deprecated in Qt 5.10. You should use sizeInBytes instead. Of course, your book was published about a month before Qt 5.10, but people probably have installed a newer version of Qt than what is used in the book.

**Comment by amahta** [comment]
Please note that **byteCount** is still usable (at least up to Qt 5.12.5)
https://doc.qt.io/qt-5/qimage-obsolete.html#byteCount

However, it is worth noting the newer method that's going to replace it:
https://doc.qt.io/qt-5/qimage.html#sizeInBytes

**Comment by tomihasa** [comment]
I just noticed there is an exported plugin in the Computer_Vision project here in GitHub. I don't know yet, if I know how to export a plugin as it has not been taught in the book (I haven't started chapter 6 yet), if I'm going to try to recreate the project.
