### ISSUE TITLE
Chapter 6: transform_plugin.cpp: Invalid number of channels in input image

### ISSUE THREAD

**Issue by tomihasa** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#13]
Error message:

libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.3) /Users/tomihasa/Downloads/opencv-3.4.3/modules/imgproc/src/color.hpp:255: error: (-2:Unspecified error) in function 'cv::CvtHelper<cv::Set<1, -1, -1>, cv::Set<3, 4, -1>, cv::Set<0, 2, 5>, cv::SizePolicy::NONE>::CvtHelper(InputArray, OutputArray, int) [VScn = cv::Set<1, -1, -1>, VDcn = cv::Set<3, 4, -1>, VDepth = cv::Set<0, 2, 5>, sizePolicy = cv::SizePolicy::NONE]'
> **Invalid number of channels in input image:**
>     'VScn::contains(scn)'
> where
>     'scn' is 3

Instead of using line:

`cvtColor(inputImage, outputImage, CV_GRAY2RGBA);
`

Use line:

`cvtColor(inputImage, outputImage, CV_32FC(1));`

**Comment by amahta** [comment]
Not sure what piece of code or section of the book this is related to. But just looking at the two lines, I'd say stick to the first one.

**Comment by tomihasa** [comment]
It is the transform_plugin.cpp file. If you give a color image to the application, the application will crash.

**Comment by sonam-packt** [comment]
@tomihasa thank you for the suggestion
