### ISSUE TITLE
QCameraImageCapture error: "Device does not support images capture."

### ISSUE THREAD

**Issue by naserpiltan** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#14]
Hello 
I am running this code in my Qt successfully but stucked in this problem :
QCameraImageCapture error: "Device does not support images capture."
what is this problem and how can solve it?

**Comment by shubham763** [comment]
Hi @naserpiltan 
It is a setup issue, please get a valid QT license and then try again.

**Comment by ViniGodoy** [comment]
Which device are you using? What is your QT version?
