### ISSUE TITLE
DWORD, LPVOID and other MSVC specific macro are not portable

### ISSUE THREAD

**Issue by avilleret** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#5]
for example :https://github.com/PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5/blob/master/ch08/MultithreadedCV/main.cpp#L18-L21

fail to build on Archlinux and certainly also on Mac OS

**Comment by amahta** [comment]
@avilleret , the following function is pasted by mistake. Remove it completely since it is not necessary and not used at all. I'll make sure to remove it now, sorry about that.

QString getVersionString(QString fName)

**Comment by amahta** [comment]
Should be fixed now. @avilleret thanks for pointing it out.
