### ISSUE TITLE
None of samples compile on Mac

### ISSUE THREAD

**Issue by pzoltowski** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#7]
I tried to compile samples but none of them work on my MacOS, e.g. regarding ch2 Hello_Qt_OpenCV I get like 20 Qt related errors. First error I think is related to Q_OBJECT macro (unknown type name 'QT_WARNING_PUSH') and then cascade of other Qt errors. It might be something related to mainwindow.ui or QMainWindow but I have no clue.

I tested my Qt 5.11 and Qt 5.12rc2 environment and both work with official samples. My OpenCV 3.4.3 setup also works (tested both C++ using Xcode and python bindings).
I'm using 
MacOS 10.13.6 High Sierra
Xcode 10.1
Qt 5.11 and Qt 5.12rc2

**Comment by pzoltowski** [comment]
solved the issue. It seems I had to modify .pro file. Previous opencv include directory pointed to '/usr/local/include'. I installed opencv and qt5 using homebrew and probably /usr/local/include also fetched some wrong qt5 headers. Below the config that worked for me (paths taken after executing in terminal 'pkg-config --cflags --libs opencv'):

unix: macx{
INCLUDEPATH += /usr/local/Cellar/opencv/3.4.3/include
LIBS += -L/usr/local/Cellar/opencv/3.4.3/lib \
-lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
}

**Comment by karlphillip** [comment]
Good.

**Comment by githubce** [comment]
Solution is in the discussion. Reopen if you want to continue discussion.
