### ISSUE TITLE
Hi, I tried to compile the sample of ch02, got this error

### ISSUE THREAD

**Issue by rocLv** [PacktPublishing/Computer-Vision-with-OpenCV-3-and-Qt5#8]
Undefined symbols for architecture x86_64:
  "cv::medianBlur(cv::_InputArray const&, cv::_OutputArray const&, int)", referenced from:
      MainWindow::on_outputPushButton_pressed() in mainwindow.o
  "cv::GaussianBlur(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)", referenced from:
      MainWindow::on_outputPushButton_pressed() in mainwindow.o
  "cv::Mat::deallocate()", referenced from:
      cv::Mat::release() in mainwindow.o
  "cv::String::deallocate()", referenced from:
      cv::String::~String() in main.o
      cv::String::operator=(cv::String const&) in main.o
      cv::String::~String() in mainwindow.o
      cv::String::operator=(cv::String const&) in mainwindow.o
      cv::String::~String() in moc_mainwindow.o
      cv::String::operator=(cv::String const&) in moc_mainwindow.o
  "cv::String::allocate(unsigned long)", referenced from:
      cv::String::String(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mainwindow.o
      cv::String::String(char const*) in mainwindow.o
  "cv::imread(cv::String const&, int)", referenced from:
      MainWindow::on_outputPushButton_pressed() in mainwindow.o
  "cv::imshow(cv::String const&, cv::_InputArray const&)", referenced from:
      MainWindow::on_outputPushButton_pressed() in mainwindow.o
  "cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      MainWindow::on_outputPushButton_pressed() in mainwindow.o
  "cv::fastFree(void*)", referenced from:
      cv::Mat::operator=(cv::Mat&&) in mainwindow.o
      cv::Mat::~Mat() in mainwindow.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Hello_Qt_OpenCV.app/Contents/MacOS/Hello_Qt_OpenCV] Error 1
17:36:19: 进程"/usr/bin/make"退出，退出代码 2 。
Error while building/deploying project Hello_Qt_OpenCV (kit: Desktop Qt 5.9.1 clang 64bit)
When executing step "Make"
17:36:19: Elapsed time: 00:07.

OS: Macbook pro 10.14
QT Creator: 5.9.1
Opencv version: 3.3.1

**Comment by amahta** [comment]
Try Clean, qmake then Build. If it doesn't help, try deleting your build folder after exiting Qt Creator.
